name: Generate Datas

on:
  schedule: # executa a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update snake versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # 🟦 Versão 1: Cobrinha redonda azul
      - name: Generate Blue Round Snake
        uses: Platane/snk@master
        with:
          github_user_name: camilafagundes
          svg_out_path: dist/github-contribution-grid-snake-blue-round.svg
          snake_color: "#1E90FF"        # azul médio
          snake_head_color: "#00BFFF"   # azul claro
          background_color: "#0D1117"   # fundo escuro
          snake_form: "round"           # formato redondo
          pixel_size: 10
          color_mode: "dark"

      # 🟪 Versão 2: Cobrinha quadrada roxa
      - name: Generate Purple Square Snake
        uses: Platane/snk@master
        with:
          github_user_name: camilafagundes
          svg_out_path: dist/github-contribution-grid-snake-purple-square.svg
          snake_color: "#A020F0"        # roxo
          snake_head_color: "#DA70D6"   # lilás
          background_color: "#0D1117"   # fundo escuro
          snake_form: "square"          # formato quadrado
          pixel_size: 10
          color_mode: "dark"

      # 🟩 Versão 3: Cobrinha redonda verde
      - name: Generate Green Round Snake
        uses: Platane/snk@master
        with:
          github_user_name: camilafagundes
          svg_out_path: dist/github-contribution-grid-snake-green-round.svg
          snake_color: "#39FF14"        # verde neon
          snake_head_color: "#00FFFF"   # ciano
          background_color: "#0D1117"   # fundo escuro
          snake_form: "round"           # formato redondo
          pixel_size: 10
          color_mode: "light"

      # 🚀 Publica todas as versões na branch 'output'
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
